### ISSUE TITLE
sh script/test_vcoco.sh，assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret) AssertionError: Range subprocess failed (exit code: 1)

### ISSUE THREAD

**Issue by li0128** [bobwan1995/PMFNet#17]
yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object/apply:numpy.core.multiarray.scalar'
  in "./test/detection_range_config.yaml", line 3, column 20
Traceback (most recent call last):
  File "tools/test_net.py", line 208, in <module>
    check_expected_results=True)
  File "/home/ps/NewDisk1/HIT_workspace/lxc/humanObjectInteraction/PMFNet-master/lib/core/test_engine.py", line 152, in run_inference
    all_results = result_getter()
  File "/home/ps/NewDisk1/HIT_workspace/lxc/humanObjectInteraction/PMFNet-master/lib/core/test_engine.py", line 125, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/ps/NewDisk1/HIT_workspace/lxc/humanObjectInteraction/PMFNet-master/lib/core/test_engine.py", line 173, in test_net_on_dataset
    args, dataset_name, proposal_file, num_images, output_dir
  File "/home/ps/NewDisk1/HIT_workspace/lxc/humanObjectInteraction/PMFNet-master/lib/core/test_engine.py", line 243, in multi_gpu_test_net_on_dataset
    opts)
  File "/home/ps/NewDisk1/HIT_workspace/lxc/humanObjectInteraction/PMFNet-master/lib/utils/subprocess.py", line 118, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/home/ps/NewDisk1/HIT_workspace/lxc/humanObjectInteraction/PMFNet-master/lib/utils/subprocess.py", line 156, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: 1)

If you suspect this is an IPython 7.11.1 bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

**Comment by bobwan1995** [comment]
yaml version problem, use the specific version pls.
